### PR TITLE
Make sure test assertion errors don't get swallowed #83

### PR DESCRIPTION
**Pull request by johngiudici**

### CODE REVIEW

**Comment by mbroadst** [comment]
Well considering we can't find a test case to break the behavior in a controllable fashion, isn't it enough to just _always_ return `Promise.reject`? I'm not really being nit-picky here I'll take this as is, but I'd like to explore the reasons why we shouldn't just use a single path

**Comment by johngiudici** [comment]
This goes a lot deeper than I thought. It actually happens with any error that can occur in the promise chain. I've managed to construct a reproducible test, but it's a bit ugly. Give me an hour and I'll throw it up and get your opinion.

**Comment by johngiudici** [comment]
Welp, my test didn't work 100%. I'll take another look at it tomorrow.

**Comment by mbroadst** [comment]
any progress here?

**Comment by johngiudici** [comment]
I haven't found a graceful way to fix or test this. Honestly, it's trivial. It doesn't affect the operation, only printing out the stack in the case of a test assertion error, and it's fairly simple to work around. 
I don't have the time right now to keep sinking into it, so I'd say just close the issue and if I figure out a fix in the future I'll put up a new PR.

**Pull request merged**
