### PR TITLE
fix #129 : adding readOnlyAttributes

### LINKED ISSUE #129: How to make some fields read-only.
excludeAttribute dose not works with Post request. Like suppose there is  'isSuperuser' field in user table which should not be open to change through any Post request. I understand that we can do it with milestones and hooks but a simple list field(readOnlyAttribute) in resource config would be great.

### PR DESCRIPTION
**Pull request by luckypur**

### CODE REVIEW

**Comment by greenify** [comment]
+1 - looks like a nice feature to me :)

**Comment by mbroadst** [comment]
@luckypur is there a reason we couldn't use `excludeAttributes` for the same thing? I thought you were asking for `excludeAttributes` to not only be excluded from the resulting output, but the input as well. Otherwise LGTM

**Comment by luckypur** [comment]
@mbroadst Actually exclude and readOnly attributes are entirely different. Like suppose i rarely want to exclude createdOn, modifiedAt kind of attributes, but they are always read only attributes for sure.

**Comment by luckypur** [comment]
@mbroadst Any update..?

**Comment by mbroadst** [comment]
@luckypur hey sorry, crazy weekend :)

I see your point, and this looks good, but could you possibly also add the code path for the update controller and include some basic tests for the functionality?

**Comment by luckypur** [comment]
@mbroadst  I am actually new to node+express, so creating a test case may take some time.  And i have observed that setting readOnlyAttributes  will disable the flexibility of modifying req.body in hooks. Like suppose i want to set 'modifiedBy' in write.before and want to make('modifiedBy')  readOnly also..! current PR will delete the modifiedBy, No matter i am setting it manually or its coming from POST requests. So i think best thing is to remove readOnlyAttributes from req.body in Controllers '_control' method in base so that all hooks are always effective. What do you think...? And yeah..Sometimes its better to be Late ... ;)

**Comment by luckypur** [comment]
@mbroadst Please have a look at updated PR.

**Comment by mbroadst** [comment]
@luckypur looks good, thanks for the contribution. I'm going to leave it in an unpublished release for now to let you and potentially others check out the feature, you will be able to get the functionality by changing your version for epilogue from `^0.6.5` to `dchester/epilogue#master`

**Comment by mbroadst** [comment]
closes #129

**Pull request merged**
