### PR TITLE
Replace merge-defaults with lodash defaultsDeep (auto-associations)

### PR DESCRIPTION
**Pull request by fmatoss**
https://github.com/dchester/epilogue/pull/87

### CODE REVIEW

**Comment by mbroadst** [comment]
@fmatoss the PR seems to break a number of tests?

**Comment by fmatoss** [comment]
In this branch not all tests passed before I made any change, these same tests failed again after the changes.

Are the tests updated? I thought in this branch some features were broken or incomplete, so I expected the errors were already known.

**Comment by mbroadst** [comment]
Sorry, it looks like I fixed the Sequelize issue in master but hadn't yet pushed it to this branch. Can you please correct the conflicts and I'll merge

**Comment by fmatoss** [comment]
Done.

**Comment by mbroadst** [comment]
@fmatoss thanks for the contribution!

**Comment by fmatoss** [comment]
You're welcome :+1:

**Pull request merged**
