### PR TITLE
Support association 'belongsTo'

### PR DESCRIPTION
**Pull request by Fridus**

### CODE REVIEW

**Comment by mbroadst** [comment]
merge in b7947ecfd65a6d568cb97517b9f2422b90ce2b86, thanks for the contribution!

**Comment by Fridus** [comment]
When this feature will be merged into master ?
I need this feature :)
Can I help you ?

**Comment by mbroadst** [comment]
unfortunately I have very little time for epilogue these days. I will certainly continue to merge and review code contributions towards completing this feature, maybe some of the other users who've requested this feature can help you out?

**Comment by Fridus** [comment]
What is missing on the feature ? I can work on it ;)
Just support `belongsToMany` ?

**Comment by mbroadst** [comment]
hasOne, hasMany, belongsToMany, these all need to be supported for at least the Read and List controllers (tests must be added for them as well). I think that would be a great place to start. There was a lot of discussion on #34 about what the semantics should be, specifically for the paths in CRUD that modify data (the C U and D), but I think if you provide the read support for this data that takes us a lot further.

Looking back now it looks like I might have already done a lot of this work on this branch, but tests are desperately needed for all of this new functionality. Perhaps @johngiudici could be helpful here, as he is working a lot with epilogue these days

**Comment by Fridus** [comment]
Currently, It's ok for `hasOne`, `hasMany` and `belongsTo` for Read and List.
There must check the tests but I think they are ok for these 3 associations.

My test when I worked on this feature :
```
Project.hasMany(Task, {
  foreignKeyConstraint: true
});
Task.belongsTo(Project, {
  foreignKey: {
     allowNull: false,
     unique: true
   },
   constraints: true,
  foreignKeyConstraint: true
});
```
-  `GET /projects/:id/tasks`
-  `GET /projects/:id/tasks/:id`
-  `GET /tasks/:id/project`

@johngiudici Hi !

**Comment by johngiudici** [comment]
Hey guys. I'm around, although admittedly this isn't a feature I've put much thought into because it's not something my implementation requires. I don't think I have anything to add to the previous discussion, but I'll be here for code reviews :)

**Pull request closed without merging**
