### PR TITLE
Mapping `delete` => `del` for Restify is not now required

### PR DESCRIPTION
**Pull request by o5**
I just tried **epilogue** with **Restify v4.0.3** and got this error:

```js
/project/node_modules/epilogue/lib/Controllers/base.js:83
  app[self.method](endpoint.string, function(req, res) {
                  ^

TypeError: app[self.method] is not a function
```

This pull resolved it.

### CODE REVIEW

**Comment by mbroadst** [comment]
@o5 hey, thanks for the contribution. Could you also update the `package.json` to update the version of restify used for testing? (This is probably why the CI run failed for your PR)

**Comment by o5** [comment]
@mbroadst hmm, I don't know why :/

**Comment by mbroadst** [comment]
yeah it looks like (from the failed tests) you're not correct, that restify indeed still uses `del` instead of `delete`?

**Comment by o5** [comment]
OMG! When I call **restify.createServer()** with some config, it ends with reported error.

You can try it, just change [this](https://github.com/dchester/epilogue/blame/master/README.md#L25) line to:
```js
app = server = restify.createServer({
      name: 'test'
})
```

**Comment by mbroadst** [comment]
@o5 wow, sounds like a bug for restify! Okay, if you modify the test to include an option on that line then it looks good. Please remember to file an issue with restify, I'm sure they wouldn't like that to slip through the cracks :smile:

**Comment by o5** [comment]
You had right. Restify [still](https://github.com/restify/node-restify/blob/e454a60ecf601b5fb37400fe45750a7a30f84a3d/lib/server.js#L467) use `del`.

**Comment by mbroadst** [comment]
Ah, sorry looks like the bug is indeed just with restify. Okay, I'll leave it to them then and close this out

**Pull request closed without merging**
