### PR TITLE
Make sure create/update return exact model

### PR DESCRIPTION
**Pull request by mterwill**
``instance`` was not always the full instance in the exact order you’d expect it in after creating/updating.

This reloads the instance from the Sequelize model to ensure you receive a copy of the data exactly as if you were to make a ``GET`` request immediately thereafter.

### CODE REVIEW

**Comment by mbroadst** [comment]
@mterwill it looks like you have some jshint errors to fix there. Also I would appreciate a test case to show your intent for this fix. I haven't found a need for this in local projects, so I'd be interested if you could submit a test case (or a few) showing the broken behavior and how this fixes it.

**Comment by mbroadst** [comment]
@mterwill ping

**Comment by mterwill** [comment]
In the screenshots below, I made a POST request and observed the following behavior that this pull request fixes:

- In the body of the POST response, there's no "description" key, though it's null anyway
- The "hidden" key is out of order

By reloading the Sequelize model, it ensures the data returned in the POST response is identical to what would be returned if a GET request was made immediately following the insert.

Functionally, there's probably no adverse effect to leaving it as-is. Aesthetically, however this ensures consistency.

## GET Request
screen shot 2015-03-27 at 12 01 49 am

## POST request/response (old)
screen shot 2015-03-26 at 11 59 46 pm

## POST request/response (new)
screen shot 2015-03-27 at 12 01 38 am

**Comment by mbroadst** [comment]
I believe https://github.com/dchester/epilogue/pull/69 closes this, please reopen if you think otherwise

**Pull request closed without merging**
